name: Get Products - Prod

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Ensure we're checking out the main branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pynacl python-dateutil

      - name: Run script
        env:
          REPO: ${{ github.repository }}
        run: |
          python request_menu.py

      - name: Commit and push changes
        if: success()  # Only run this step if the previous steps were successful
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated stores/menu listings as of $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          git push origin prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
